output_dir: .

clear_top_level: true
logical_grouping: true

collections:
    - common
    - purescript

loader_paths:
    - docs

render_context:
    project:
        project_name: purescript-chalk
        version: 0.1.0

        verbose_name: PureScript chalk
        description: PureScript FFI bindings for Chalk.

        repository: https://github.com/JoelLefkowitz/purescript-chalk
        codacy_id: c2aa0dd2fc2a470ba3cdc6407167a3e0

        inserts:
            - usage.md

    author:
        author: Joel Lefkowitz
        author_email: joellefkowitz@hotmail.com
        author_github_handle: joellefkowitz

    package:
        is_pursuit_package: true
        package_name: chalk

    portfolio:
        is_portfolio: true
        status_level: 1

        languages:
            - PureScript

        paradigms:
            - Functional programming
